<?xml version="1.0" ?>
<robot name="omnibot3" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- ================= ARGUMENTOS ================= -->
  <xacro:arg name="ns" default="r1"/>
  <xacro:arg name="robot_base_color" default="0.0 0.0 1.0 0.95"/> <!-- RGBA -->

  <!-- ================= PROPIEDADES ================= -->
  <xacro:property name="package_name" value="ign_robots_examples"/>
  <xacro:property name="PI" value="3.14159265"/>

  <xacro:property name="L_x" value="0.085"/>
  <xacro:property name="L_y" value="0.14"/>
  <xacro:property name="base_elevation" value="0.08"/>
  <xacro:property name="wheelDiameter" value="0.1"/>
  <xacro:property name="wheelThickness" value="0.05"/>

  <!-- ================= BASE ================= -->
  <link name="$(arg ns)/base_footprint"/>

  <joint name="$(arg ns)/base_joint" type="fixed">
    <parent link="$(arg ns)/base_footprint"/>
    <child link="$(arg ns)/base_link"/>
    <origin xyz="0 0 ${base_elevation}" rpy="0 0 0"/>
  </joint>

  <link name="$(arg ns)/base_link">
    <visual>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.2 0.005"/>
      </geometry>
      <material name="base_color">
        <color rgba="$(arg robot_base_color)"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.2 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="20.0"/>
      <inertia ixx="2.133" ixy="0" ixz="0" iyy="4.266" iyz="0" izz="5.546"/>
    </inertial>
  </link>

  <!-- ================= WHEELS MACRO ================= -->
  <xacro:macro name="wheel" params="prefix parent_link joint_xyz joint_rpy visual_xyz visual_rpy wheelSide">
    <joint name="${prefix}_joint" type="continuous">
      <parent link="${parent_link}"/>
      <child link="${prefix}_link"/>
      <origin xyz="${joint_xyz}" rpy="${joint_rpy}"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${prefix}_link">
      <visual>
        <origin xyz="${visual_xyz}" rpy="${visual_rpy}"/>
        <geometry>
          <mesh filename="package://${package_name}/meshes/${wheelSide}_mecanum_wheel.dae" scale="1.0 0.8 1.0"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheelDiameter/2}" length="${wheelThickness}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="6.1e-5" ixy="0" ixz="0" iyy="6.1e-5" iyz="0" izz="6.1e-5"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- ================= INSTANTIATE WHEELS ================= -->
  <xacro:wheel prefix="leftfront" parent_link="$(arg ns)/base_link" joint_xyz="${L_x} ${L_y} 0.01"
    joint_rpy="${-PI/2} 0 0" visual_xyz="0 0 0" visual_rpy="${-PI/2} 0 0" wheelSide="left"/>
  <xacro:wheel prefix="rightfront" parent_link="$(arg ns)/base_link" joint_xyz="${L_x} ${-L_y} 0.01"
    joint_rpy="${-PI/2} 0 0" visual_xyz="0 0 0" visual_rpy="${-PI/2} 0 0" wheelSide="right"/>
  <xacro:wheel prefix="rightback" parent_link="$(arg ns)/base_link" joint_xyz="${-L_x} ${-L_y} 0.01"
    joint_rpy="${-PI/2} 0 0" visual_xyz="0 0 0" visual_rpy="${-PI/2} 0 0" wheelSide="left"/>
  <xacro:wheel prefix="leftback" parent_link="$(arg ns)/base_link" joint_xyz="${-L_x} ${L_y} 0.01"
    joint_rpy="${-PI/2} 0 0" visual_xyz="0 0 0" visual_rpy="${-PI/2} 0 0" wheelSide="right"/>

  <!-- ================= SENSORS ================= -->
  <!-- IMU -->
  <gazebo reference="$(arg ns)/base_link">
    <sensor name="imu_sensor" type="imu">
      <ignition_frame_id>$(arg ns)/base_link</ignition_frame_id>
      <always_on>1</always_on>
      <update_rate>50</update_rate>
      <visualize>false</visualize>
      <topic>$(arg ns)/imu</topic>
      <imu>
        <enable_orientation>1</enable_orientation>
      </imu>
    </sensor>
  </gazebo>

  <!-- LIDAR -->
  <joint name="$(arg ns)/lidar_joint" type="fixed">
    <parent link="$(arg ns)/base_link"/>
    <child link="$(arg ns)/lidar_link"/>
    <origin xyz="0 0 0.07" rpy="0 0 0"/>
  </joint>
  <link name="$(arg ns)/lidar_link"/>
  <gazebo reference="$(arg ns)/lidar_link">
    <sensor name="gpu_lidar" type="gpu_lidar">
      <ignition_frame_id>$(arg ns)/lidar_link</ignition_frame_id>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>${-PI}</min_angle>
            <max_angle>${PI}</max_angle>
          </horizontal>
          <vertical>
            <samples>16</samples>
            <resolution>1</resolution>
            <min_angle>-0.261799</min_angle>
            <max_angle>0.261799</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.1</min>
          <max>20.0</max>
        </range>
      </ray>
      <always_on>1</always_on>
      <visualize>false</visualize>
      <topic>$(arg ns)/lidar</topic>
    </sensor>
  </gazebo>

  <!-- RGB CAMERA -->
  <joint name="$(arg ns)/camera_joint" type="fixed">
    <parent link="$(arg ns)/base_link"/>
    <child link="$(arg ns)/camera_frame"/>
    <origin xyz="0.1 0 0.08" rpy="0 0 0"/>
  </joint>
  <link name="$(arg ns)/camera_frame"/>
  <gazebo reference="$(arg ns)/camera_frame">
    <sensor name="camera" type="camera">
      <ignition_frame_id>$(arg ns)/camera_frame</ignition_frame_id>
      <always_on>1</always_on>
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <topic>$(arg ns)/camera/image_raw</topic>
    </sensor>
  </gazebo>

  <!-- RGBD CAMERA -->
  <joint name="$(arg ns)/rgbd_camera_joint" type="fixed">
    <parent link="$(arg ns)/base_link"/>
    <child link="$(arg ns)/rgbd_camera_frame"/>
    <origin xyz="0.05 0 0.06" rpy="0 ${-PI/4} 0"/>
  </joint>
  <link name="$(arg ns)/rgbd_camera_frame"/>
  <gazebo reference="$(arg ns)/rgbd_camera_frame">
    <sensor name="rgbd_camera" type="rgbd_camera">
      <ignition_frame_id>$(arg ns)/rgbd_camera_frame</ignition_frame_id>
      <always_on>1</always_on>
      <update_rate>10</update_rate>
      <visualize>false</visualize>
      <topic>$(arg ns)/depth_camera</topic>
    </sensor>
  </gazebo>

  <!-- ================= GAZEBO PLUGINS ================= -->
  <gazebo>
    <plugin filename="libignition-gazebo-mecanum-drive-system.so" name="ignition::gazebo::systems::MecanumDrive">
      <update_rate>20</update_rate>
      <front_left_joint>leftfront_joint</front_left_joint>
      <front_right_joint>rightfront_joint</front_right_joint>
      <back_left_joint>leftback_joint</back_left_joint>
      <back_right_joint>rightback_joint</back_right_joint>
      <wheel_separation>${L_x}</wheel_separation>
      <wheelbase>${L_y}</wheelbase>
      <wheel_radius>${wheelDiameter/2}</wheel_radius>
      <min_acceleration>-5</min_acceleration>
      <max_acceleration>5</max_acceleration>
    </plugin>

    <plugin filename="libignition-gazebo-odometry-publisher-system.so" name="ignition::gazebo::systems::OdometryPublisher">
      <dimensions>2</dimensions>
      <robot_base_frame>$(arg ns)/base_link</robot_base_frame>
    </plugin>

     <plugin
      filename="gz-sim-joint-state-publisher-system"
      name="gz::sim::systems::JointStatePublisher">
    </plugin>
    
      
  </gazebo>

</robot>