<?xml version="1.0" ?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- This mobile robot moves as a diff-drive robot -->

  <!-- In xacro:if, any string different from '' means true -->
  <xacro:arg name="with_light" default=""/>

  <xacro:property name="package_name" value="ign_robots_examples"/>
  <xacro:property name="PI" value="3.14159265"/>
  
  <xacro:property name="L_x" value="0.085"/> <!-- Robot X axis (front-back) -->
  <xacro:property name="L_y" value="0.14"/>  <!-- Robot Y axis (left-right) -->
  <xacro:property name="base_elevation" value="0.08"/>
  <xacro:property name="wheelDiameter" value="0.1"/>
  <xacro:property name="wheelThickness" value="0.05"/>


  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_elevation}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.2 0.005"/><!-- Main block -->
      </geometry>
      <material name="grey">
        <color rgba="0.8 0.8 0.8 1.0"/>
      </material>
    </visual>
    <!-- Frontal part to define the robot orientation -->
    <visual>
      <origin xyz="0.1 0 0.045" rpy="0 0 0"/>
      <geometry>
        <box size="0.07 0.076 0.03"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.2 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <mass value="20.0"/>
      <inertia ixx="2.133" ixy="0" ixz="0" iyy="4.266" iyz="0" izz="5.546" />
    </inertial>
  </link>


  <!-- WHEEL MACRO --> 
  <xacro:macro name="wheel" params="prefix parent_link joint_origin_xyz joint_origin_rpy visual_origin_xyz visual_origin_rpy wheelSide">
    <joint name="${prefix}_joint" type="continuous">
      <origin xyz="${joint_origin_xyz}" rpy="${joint_origin_rpy}"/>
      <parent link="${parent_link}"/>
      <child link="${prefix}_link"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${prefix}_link">
      <visual>
        <origin xyz="${visual_origin_xyz}" rpy="${visual_origin_rpy}"/>
        <geometry>
          <mesh filename="package://${package_name}/meshes/${wheelSide}_mecanum_wheel.dae" scale="1.0 0.8 1.0"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheelThickness}" radius="${wheelDiameter/2}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.1" />
        <inertia ixx="6.1e-5" ixy="0" ixz="0" iyy="6.1e-5" iyz="0" izz="6.1e-5"/>
      </inertial>
    </link>  
  </xacro:macro>
  
  
  <!-- Wheels definition (joints and links USING MACROS) -->
  <!-- left_front_wheel (M1) -->
  <xacro:wheel prefix="leftfront" parent_link="base_link" joint_origin_xyz="${L_x} ${L_y} 0.01" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="left"/>
  
  <!-- right_front_wheel (M2) -->
  <xacro:wheel prefix="rightfront" parent_link="base_link" joint_origin_xyz="${L_x} ${-L_y} 0.01" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="right"/>
  
  <!-- right_back_wheel (M3) -->
  <xacro:wheel prefix="rightback" parent_link="base_link" joint_origin_xyz="${-L_x} ${-L_y} 0.01" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="left"/>
  
  <!-- left_back_wheel (M4) -->
  <xacro:wheel prefix="leftback" parent_link="base_link" joint_origin_xyz="${-L_x} ${L_y} 0.01" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="right"/>

  <!-- CONDITIONAL MACRO. ADD A SIMPLE LIGHT ATTACHED TO ANY LINK. type=[spot, point, directional] -->
  <xacro:if value="${ '$(arg with_light)' != ''}" > <!-- == 'true' does not work -->
    <gazebo reference="base_link"> 
      <light name='led_light' type='spot'>
        <pose>0.06 0 0.05 0 0 0</pose>       
        <cast_shadows>true</cast_shadows>
        <intensity>1</intensity>
        <diffuse>0 1 0 1</diffuse> <!-- color (rgba) -->
        <direction>1 0 0</direction> <!-- X=1 forward, Z=-1 downward -->
        <attenuation>
          <range>0.5</range>
          <linear>0.01</linear>
          <constant>0.1</constant>
          <quadratic>0.001</quadratic>
        </attenuation>
        <spot>
          <inner_angle>0.1</inner_angle>
          <outer_angle>1</outer_angle>
          <falloff>1</falloff>
        </spot>
      </light>
    </gazebo>
  </xacro:if>


  <gazebo>
    <plugin filename="ignition-gazebo-mecanum-drive-system" name="ignition::gazebo::systems::MecanumDrive">
      <front_left_joint>leftfront_joint</front_left_joint>
      <front_right_joint>rightfront_joint</front_right_joint>
      <back_left_joint>leftback_joint</back_left_joint>
      <back_right_joint>rightback_joint</back_right_joint>
      <wheel_separation>${L_x}</wheel_separation>       <!--Lx-->
      <wheelbase>${L_y}</wheelbase>                     <!--Ly-->
      <wheel_radius>${wheelDiameter/2}</wheel_radius>
      <min_acceleration>-5</min_acceleration>
      <max_acceleration>5</max_acceleration>
    </plugin>

    <!-- World odometry plugin (by default, odometry topic is used) -->
    <plugin filename="ignition-gazebo-odometry-publisher-system"
      name="ignition::gazebo::systems::OdometryPublisher">
      <dimensions>2</dimensions>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
        
    <plugin
      filename="ignition-gazebo-joint-state-publisher-system"
      name="ignition::gazebo::systems::JointStatePublisher">
    </plugin>
      
  </gazebo>
  
</robot>
