<?xml version="1.0" ?>
<robot name="omnibot2" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- ARGUMENTS -->
  <xacro:arg name="with_light" default=""/>

  <!-- PROPERTIES -->
  <xacro:property name="package_name" value="ign_robots_examples"/>
  <xacro:property name="PI" value="3.14159265"/>
  <xacro:property name="L_x" value="0.085"/>
  <xacro:property name="L_y" value="0.14"/>
  <xacro:property name="base_elevation" value="0.08"/>
  <xacro:property name="wheelDiameter" value="0.1"/>
  <xacro:property name="wheelThickness" value="0.05"/>
  <xacro:property name="wheel_radius" value="${wheelDiameter/2}"/>

  <!-- BASE -->
  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_elevation}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.2 0.005"/>
      </geometry>
      <material name="grey">
        <color rgba="0.8 0.8 0.8 1.0"/>
      </material>
    </visual>
    <visual>
      <origin xyz="0.1 0 0.045" rpy="0 0 0"/>
      <geometry>
        <box size="0.07 0.076 0.03"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.2 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <mass value="20.0"/>
      <inertia ixx="2.133" ixy="0" ixz="0" iyy="4.266" iyz="0" izz="5.546"/>
    </inertial>
  </link>

  <!-- WHEEL MACRO -->
  <xacro:macro name="wheel" params="prefix parent_link joint_origin_xyz joint_origin_rpy visual_origin_xyz visual_origin_rpy wheelSide">
    <joint name="${prefix}_joint" type="continuous">
      <origin xyz="${joint_origin_xyz}" rpy="${joint_origin_rpy}"/>
      <parent link="${parent_link}"/>
      <child link="${prefix}_link"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${prefix}_link">
      <visual>
        <origin xyz="${visual_origin_xyz}" rpy="${visual_origin_rpy}"/>
        <geometry>
          <mesh filename="package://${package_name}/meshes/${wheelSide}_mecanum_wheel.dae" scale="1.0 0.8 1.0"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheelThickness}" radius="${wheelDiameter/2}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.1"/>
        <inertia ixx="6.1e-5" ixy="0" ixz="0" iyy="6.1e-5" iyz="0" izz="6.1e-5"/>
      </inertial>
    </link>  
  </xacro:macro>

  <!-- Wheels -->
  <xacro:wheel prefix="leftfront" parent_link="base_link" joint_origin_xyz="${L_x} ${L_y} 0.01" joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="left"/>
  <xacro:wheel prefix="rightfront" parent_link="base_link" joint_origin_xyz="${L_x} ${-L_y} 0.01" joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="right"/>
  <xacro:wheel prefix="rightback" parent_link="base_link" joint_origin_xyz="${-L_x} ${-L_y} 0.01" joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="left"/>
  <xacro:wheel prefix="leftback" parent_link="base_link" joint_origin_xyz="${-L_x} ${L_y} 0.01" joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="right"/>

  <!-- Optional light -->
  <xacro:if value="${ '$(arg with_light)' != ''}">
    <gazebo reference="base_link"> 
      <light name='led_light' type='spot'>
        <pose>0.06 0 0.05 0 0 0</pose>
        <cast_shadows>true</cast_shadows>
        <intensity>1</intensity>
        <diffuse>0 1 0 1</diffuse>
        <direction>1 0 0</direction>
        <attenuation>
          <range>0.5</range>
          <linear>0.01</linear>
          <constant>0.1</constant>
          <quadratic>0.001</quadratic>
        </attenuation>
        <spot>
          <inner_angle>0.1</inner_angle>
          <outer_angle>1</outer_angle>
          <falloff>1</falloff>
        </spot>
      </light>
    </gazebo>
  </xacro:if>

  <!-- SENSOR LINKS -->

  <!-- Lidar -->
  <link name="lidar_link"/>
  <joint name="lidar_joint" type="fixed">
    <parent>base_link</parent>
    <child>lidar_link</child>
    <origin xyz="0 0 0.08" rpy="0 0 0"/>
  </joint>
  <sensor name="gpu_lidar" type="gpu_lidar">
    <pose>0 0 0 0 0 0</pose>
    <topic>${robot_ns}/lidar</topic>
    <update_rate>15</update_rate>
    <lidar>
      <scan>
        <horizontal>
          <samples>640</samples>
          <resolution>1</resolution>
          <min_angle>-1.396263</min_angle>
          <max_angle>1.396263</max_angle>
        </horizontal>
        <vertical>
          <samples>1</samples>
          <resolution>1</resolution>
          <min_angle>0.0</min_angle>
          <max_angle>0.0</max_angle>
        </vertical>
      </scan>
      <range>
        <min>0.3</min>
        <max>3.0</max>
        <resolution>0.01</resolution>
      </range>
    </lidar>
    <always_on>1</always_on>
    <visualize>true</visualize>
  </sensor>

  <!-- RGB Camera -->
  <link name="camera_link"/>
  <joint name="camera_joint" type="fixed">
    <parent>base_link</parent>
    <child>camera_link</child>
    <origin xyz="0.14 0 0.125" rpy="0 0 0"/>
  </joint>
  <sensor name="camera" type="camera">
    <camera>
      <horizontal_fov>1.047</horizontal_fov>
      <image>
        <width>320</width>
        <height>240</height>
      </image>
      <clip>
        <near>0.1</near>
        <far>100</far>
      </clip>
    </camera>
    <always_on>1</always_on>
    <update_rate>30</update_rate>
    <visualize>true</visualize>
    <topic>${robot_ns}/camera</topic>
  </sensor>

  <!-- Depth Camera / RGB-D -->
  <link name="depth_camera_link"/>
  <joint name="depth_camera_joint" type="fixed">
    <parent>base_link</parent>
    <child>depth_camera_link</child>
    <origin xyz="0.14 0 0.12" rpy="0 0 0"/>
  </joint>
  <sensor name="depth_camera" type="camera">
    <camera>
      <horizontal_fov>1.047</horizontal_fov>
      <image>
        <width>320</width>
        <height>240</height>
      </image>
      <clip>
        <near>0.1</near>
        <far>10.0</far>
      </clip>
    </camera>
    <always_on>1</always_on>
    <update_rate>30</update_rate>
    <visualize>true</visualize>
    <topic>${robot_ns}/depth_camera/image</topic>
  </sensor>

  <!-- IMU -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <parent>base_link</parent>
    <child>imu_link</child>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
  </joint>
  <sensor name="imu" type="imu">
    <imu>
      <angular_velocity>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </angular_velocity>
      <linear_acceleration>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </linear_acceleration>
    </imu>
    <always_on>1</always_on>
    <update_rate>50</update_rate>
    <visualize>true</visualize>
    <topic>${robot_ns}/imu</topic>
  </sensor>

  <!-- GAZEBO PLUGINS -->
  <gazebo>
    <plugin filename="ignition-gazebo-mecanum-drive-system" name="ignition::gazebo::systems::MecanumDrive">
      <front_left_joint>leftfront_joint</front_left_joint>
      <front_right_joint>rightfront_joint</front_right_joint>
      <back_left_joint>leftback_joint</back_left_joint>
      <back_right_joint>rightback_joint</back_right_joint>
      <wheel_separation>${L_x}</wheel_separation>
      <wheelbase>${L_y}</wheelbase>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <min_acceleration>-5</min_acceleration>
      <max_acceleration>5</max_acceleration>
    </plugin>

    <plugin filename="ignition-gazebo-odometry-publisher-system" name="ignition::gazebo::systems::OdometryPublisher">
      <dimensions>2</dimensions>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>

    <plugin filename="ignition-gazebo-joint-state-publisher-system" name="ignition::gazebo::systems::JointStatePublisher"/>
  </gazebo>

</robot>
