<?xml version="1.0" ?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="package_name" value="ign_robots_examples"/>
  <xacro:property name="PI" value="3.14159265"/>
  
  <xacro:property name="L_x" value="0.4"/> <!-- Robot X axis (front-back) -->
  <xacro:property name="L_y" value="0.5"/>  <!-- Robot Y axis (left-right) -->
  <xacro:property name="base_elevation" value="0.14"/>
  <xacro:property name="wheelDiameter" value="0.35"/>
  <xacro:property name="wheelThickness" value="0.15"/>
  

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_elevation}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${2*L_x+0.3} ${2*L_y-0.2} 0.1"/><!-- Main block -->
      </geometry>
      <material name="d">
        <color rgba="0.2 0.2 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <box size="${2*L_x+0.3} ${2*L_y-0.2} 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <mass value="20.0"/>
      <inertia ixx="2.133" ixy="0" ixz="0" iyy="4.266" iyz="0" izz="5.546"/>
    </inertial>
  </link>


  <!-- WHEEL MACRO --> 
  <xacro:macro name="wheel" params="prefix parent_link joint_origin_xyz joint_origin_rpy visual_origin_xyz visual_origin_rpy wheelSide">
    <joint name="${prefix}_joint" type="continuous">
      <origin xyz="${joint_origin_xyz}" rpy="${joint_origin_rpy}"/>
      <parent link="${parent_link}"/>
      <child link="${prefix}_link"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${prefix}_link">
      <visual>
        <origin xyz="${visual_origin_xyz}" rpy="${visual_origin_rpy}"/>
        <geometry>
          <mesh filename="package://${package_name}/meshes/husky_wheel.stl" scale="1.0 0.9 1.0"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheelThickness}" radius="${wheelDiameter/2}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.1" />
        <inertia ixx="6.1e-5" ixy="0" ixz="0" iyy="6.1e-5" iyz="0" izz="6.1e-5"/>
      </inertial>
    </link>  
  </xacro:macro>
  
  
  <!-- Wheels definition (joints and links USING MACROS) -->
  <!-- left_front_wheel (M1) -->
  <xacro:wheel prefix="leftfront" parent_link="base_link" joint_origin_xyz="${L_x} ${L_y} 0.01" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="left"/>
  
  <!-- right_front_wheel (M2) -->
  <xacro:wheel prefix="rightfront" parent_link="base_link" joint_origin_xyz="${L_x} ${-L_y} 0.01" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="right"/>
  
  <!-- right_back_wheel (M3) -->
  <xacro:wheel prefix="rightback" parent_link="base_link" joint_origin_xyz="${-L_x} ${-L_y} 0.01" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="left"/>
  
  <!-- left_back_wheel (M4) -->
  <xacro:wheel prefix="leftback" parent_link="base_link" joint_origin_xyz="${-L_x} ${L_y} 0.01" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="right"/>


  <gazebo>
    <plugin
      filename="ignition-gazebo-diff-drive-system"
      name="ignition::gazebo::systems::DiffDrive">
      <left_joint>leftfront_joint</left_joint>
      <left_joint>leftback_joint</left_joint>
      <right_joint>rightfront_joint</right_joint>
      <right_joint>rightback_joint</right_joint>
      <wheel_separation>${2*L_x}</wheel_separation>
      <wheel_radius>${wheelDiameter/2}</wheel_radius>
      <odom_publish_frequency>20</odom_publish_frequency>
      <max_linear_acceleration>0.5</max_linear_acceleration>
      <min_linear_acceleration>-0.5</min_linear_acceleration>
      <max_angular_acceleration>1</max_angular_acceleration>
      <min_angular_acceleration>-1</min_angular_acceleration>
      <max_linear_velocity>1.0</max_linear_velocity>
      <min_linear_velocity>-0.5</min_linear_velocity>
      <max_angular_velocity>1</max_angular_velocity>
      <min_angular_velocity>-1</min_angular_velocity>
      <odom_topic>encoder</odom_topic> <!-- THIS TAG IS REQUIRED TO USE THE WORLD PLUING -->
    </plugin>

    <!-- World odometry plugin -->
    <plugin filename="ignition-gazebo-odometry-publisher-system"
      name="ignition::gazebo::systems::OdometryPublisher">
      <dimensions>3</dimensions>
      <robot_base_frame>base_footprint</robot_base_frame>
      <!-- <publish_link_pose>true</publish_link_pose> -->
    </plugin>


    <!-- <plugin
    filename="gz-sim-pose-publisher-system"
    name="gz::sim::systems::PosePublisher">
    <publish_link_pose>true</publish_link_pose>
    <use_pose_vector_msg>true</use_pose_vector_msg>
    <publish_nested_model_pose>true</publish_nested_model_pose>
    </plugin> -->
        
    <plugin
      filename="ignition-gazebo-joint-state-publisher-system"
      name="ignition::gazebo::systems::JointStatePublisher">
    </plugin>
      
  </gazebo>
  
</robot>
