amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "r1/base_footprint"
    odom_frame_id: "/odom"
    scan_topic: "/scan"
    global_frame_id: "/map"
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.25
    update_min_a: 0.2
    resample_interval: 1

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "config/map.yaml"

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.0
      max_vel_x: 0.26
      min_vel_y: -0.26
      max_vel_y: 0.26
      min_vel_theta: -1.0
      max_vel_theta: 1.0
      acc_lim_x: 2.5
      acc_lim_y: 2.5
      acc_lim_theta: 3.2

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

behavior_server:
  ros__parameters:
    use_sim_time: true
    behavior_plugins: ["spin", "backup", "drive_on_heading"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    plugin: "nav2_waypoint_follower/WaypointFollower"
